class StudentAssessments():
    def __init__(self):
        self.define = {
            "Phẩm chất": {
                "Yêu nước": [
                    "Yêu thiên nhiên và có những việc làm thiết thực bảo vệ thiên nhiên.",
                    "Yêu quê hương, yêu Tổ quốc, tôn trọng các biểu trưng của đất nước.",
                    "Kính trọng, biết ơn người lao động, người có công với quê hương, đất nước; tham gia các hoạt động đền ơn, đáp nghĩa đối với những người có công với quê hương, đất nước."
                ],
                "Nhân ái": [
                    "Yêu thương, quan tâm, chăm sóc người thân trong gia đình.",
                    "Yêu quý bạn bè, thầy cô; quan tâm, động viên, khích lệ bạn bè.",
                    "Tôn trọng người lớn tuổi; giúp đỡ người già, người ốm yếu, người khuyết tật; nhường nhịn và giúp đỡ em nhỏ.",
                    "Biết chia sẻ với những bạn có hoàn cảnh khó khăn, các bạn ở vùng sâu, vùng xa, người khuyết tật và đồng bào bị ảnh hưởng của thiên tai.",
                    "Tôn trọng sự khác biệt của bạn bè trong lớp về cách ăn mặc, tính nết và hoàn cảnh gia đình.",
                    "Không phân biệt đối xử, chia rẽ các bạn.","Sẵn sàng tha thứ cho những hành vi có lỗi của bạn."
                ],
                "Chăm chỉ": [
                    "Đi học đầy đủ, đúng giờ.",
                    "Thường xuyên hoàn thành nhiệm vụ học tập.",
                    "Ham học hỏi, thích đọc sách để mở rộng hiểu biết.",
                    "Có ý thức vận dụng kiến thức, kĩ năng học được ở nhà trường vào đời sống hằng ngày.",
                    "Thường xuyên tham gia các công việc của gia đình vừa sức với bản thân.",
                    "Thường xuyên tham gia các công việc của trường lớp, cộng đồng vừa sức với bản thân."
                ],
                "Trung thực": [
                    "Trung thực, thật thà, ngay thẳng trong học tập, lao động và sinh hoạt hằng ngày; mạnh dạn nói lên ý kiến của mình.",
                    "Luôn giữ lời hứa; mạnh dạn nhận lỗi, sửa lỗi và bảo vệ cái đúng, cái tốt.",
                    "Không tự tiện lấy đồ vật, tiền bạc của người thân, bạn bè, thầy cô và những người khác.",
                    "Không đồng tình với các hành vi thiếu trung thực trong học tập và trong cuộc sống."
                ],
                "Trách nhiệm": [
                    "Có ý thức giữ gìn vệ sinh, rèn luyện thân thể, chăm sóc sức khoẻ.",
                    "Có ý thức sinh hoạt nền nếp.",
                    "Có ý thức bảo quản, giữ gìn đồ dùng cá nhân và gia đình.",
                    "Không bỏ thừa đồ ăn, thức uống; có ý thức tiết kiệm tiền bạc, điện nước trong gia đình.",
                    "Tự giác thực hiện nghiêm túc nội quy của nhà trường và các quy định, quy ước của tập thể; giữ vệ sinh chung; bảo vệ của công.",
                    "Không gây mất trật tự, cãi nhau, đánh nhau.",
                    "Nhắc nhở bạn bè chấp hành nội quy trường lớp; nhắc nhở người thân chấp hành các quy định, quy ước nơi công cộng.",
                    "Có trách nhiệm với công việc được giao ở trường, ở lớp.",
                    "Tích cực tham gia các hoạt động tập thể, hoạt động xã hội phù hợp với lứa tuổi.",
                    "Có ý thức chăm sóc, bảo vệ cây xanh và các con vật có ích.",
                    "Có ý thức giữ vệ sinh môi trường, không xả rác bừa bãi.",
                    "Không đồng tình với những hành vi xâm hại thiên nhiên."
                ]
            },
            "Năng lực chung": {
                "Tự chủ và tự học": [
                    "Tự làm được những việc của mình ở nhà và ở trường theo sự phân công, hướng dẫn.",
                    "Có ý thức về quyền và mong muốn của bản thân; bước đầu biết cách trình bày và thực hiện một số quyền lợi và nhu cầu chính đáng.",
                    "Nhận biết và bày tỏ được tình cảm, cảm xúc của bản thân; biết chia sẻ tình cảm, cảm xúc của bản thân với người khác.",
                    "Hoà nhã với mọi người; không nói hoặc làm những điều xúc phạm người khác.",
                    "Thực hiện đúng kế hoạch học tập, lao động; không mải chơi, làm ảnh hưởng đến việc học và các việc khác.",
                    "Tìm được những cách giải quyết khác nhau cho cùng một vấn đề.",
                    "Thực hiện được các nhiệm vụ khác nhau với những yêu cầu khác nhau.",
                    "Bộc lộ được sở thích, khả năng của bản thân.",
                    "Biết tên, hoạt động chính và vai trò của một số nghề nghiệp; liên hệ được những hiểu biết đó với nghề nghiệp của người thân trong gia đình.",
                    "Có ý thức tổng kết và trình bày được những điều đã học.",
                    "Nhận ra và sửa chữa sai sót trong bài kiểm tra qua lời nhận xét của thầy cô.",
                    "Có ý thức học hỏi thầy cô, bạn bè và người khác để củng cố và mở rộng hiểu biết.",
                    "Có ý thức học tập và làm theo những gương người tốt."
                ],
                "Giao tiếp và hợp tác": [
                    "Nhận ra được ý nghĩa của giao tiếp trong việc đáp ứng các nhu cầu của bản thân.",
                    "Tiếp nhận được những văn bản về đời sống, tự nhiên và xã hội có sử dụng ngôn ngữ kết hợp với hình ảnh như truyện tranh, bài viết đơn giản.",
                    "Bước đầu biết sử dụng ngôn ngữ kết hợp với hình ảnh, cử chỉ để trình bày thông tin và ý tưởng.",
                    "Tập trung chú ý khi giao tiếp; nhận ra được thái độ của đối tượng giao tiếp.",
                    "Biết cách kết bạn và giữ gìn tình bạn.",
                    "Nhận ra được những bất đồng, xích mích giữa bản thân với bạn hoặc giữa các bạn với nhau; biết nhường bạn hoặc thuyết phục bạn.",
                    "Có thói quen trao đổi, giúp đỡ nhau trong học tập; biết cùng nhau hoàn thành nhiệm vụ học tập theo sự hướng dẫn của thầy cô.",
                    "Hiểu được nhiệm vụ của nhóm và trách nhiệm, hoạt động của bản thân trong nhóm sau khi được hướng dẫn, phân công.",
                    "Nhận biết được một số đặc điểm nổi bật của các thành viên trong nhóm để đề xuất phương án phân công công việc phù hợp.",
                    "Biết cố gắng hoàn thành phần việc mình được phân công và chia sẻ giúp đỡ thành viên khác cùng hoàn thành việc được phân công.",
                    "Báo cáo được kết quả thực hiện nhiệm vụ của cả nhóm; tự nhận xét được ưu điểm, thiếu sót của bản thân theo hướng dẫn của thầy cô.",
                    "Có hiểu biết ban đầu về một số nước trong khu vực và trên thế giới.",
                    "Biết tham gia một số hoạt động hội nhập quốc tế theo hướng dẫn của nhà trường."
                ],
                "Giải quyết vấn đề và sáng tạo": [
                    "Biết xác định và làm rõ thông tin, ý tưởng mới đối với bản thân từ các nguồn tài liệu cho sẵn theo hướng dẫn.",
                    "Biết thu nhận thông tin từ tình huống, nhận ra những vấn đề đơn giản và đặt được câu hỏi.",
                    "Dựa trên hiểu biết đã có, biết hình thành ý tưởng mới đối với bản thân và dự đoán được kết quả khi thực hiện.",
                    "Dựa trên hiểu biết đã có, biết hình thành ý tưởng mới đối với bản thân và dự đoán được kết quả khi thực hiện.",
                    "Xác định được nội dung chính và cách thức hoạt động để đạt mục tiêu đặt ra theo hướng dẫn.",
                    "Nhận xét được ý nghĩa của các hoạt động.",
                    "Nêu được thắc mắc về sự vật, hiện tượng xung quanh; không e ngại nêu ý kiến cá nhân trước các thông tin khác nhau về sự vật, hiện tượng; sẵn sàng thay đổi khi nhận ra sai sót."
                ]
            },
            "Môn học":{
                "Tiếng Việt": {
                    "Biết": [
                        "đọc thuộc lòng bài thơ",
                        "đọc thuộc lòng đoạn văn",
                        "kể lại câu chuyện đã đọc",
                        "kể lại sự việc đã chứng kiến",
                        "nhận biết đặc điểm kiểu văn bản",
                        "nhận biết đặc điểm thể loại",
                        "nhận biết tính toàn vẹn của văn bản",
                        "nhận biết tính chỉnh thể của văn bản",
                        "nhận biết lí lẽ, bằng chứng, thông tin",
                        "nhận biết biện pháp tu từ"
                    ],
                    "Hiểu": [
                        "nhận biết chủ đề",
                        "nhận biết thông điệp",
                        "phân tích chủ đề",
                        "phân tích thông điệp",
                        "nhận biết tình cảm của người viết",
                        "nhận biết cảm xúc của người viết",
                        "phân tích tình cảm của người viết",
                        "phân tích cảm xúc của người viết",
                        "nhận biết cách triển khai ý tưởng",
                        "phân tích cách triển khai ý tưởng",
                        "hiểu đề tài",
                        "hiểu thông tin",
                        "hiểu cảm hứng chủ đạo",
                        "xác định đề tài",
                        "xác định thông tin",
                        "xác định cảm hứng chủ đạo",
                        "phân tích đặc điểm kiểu văn bản",
                        "phân tích đặc điểm thể loại",
                        "hiểu chủ đề",
                        "hiểu thông tin cơ bản",
                        "giải thích tác dụng của biện pháp tu từ"
                        "tóm tắt các ý chính của một đoạn",
                        "tóm tắt nội dung của văn bản",
                        "nhận xét nội dung",
                        "đánh giá nội dung",
                        "nhận xét hình thức",
                        "đánh giá hình thức",
                        "nhận xét các biện pháp nghệ thuật",
                        "đánh giá các biện pháp nghệ thuật",
                        "nhận xét cách lập luận",
                        "đánh giá cách lập luận",
                        "nhận xét đề tài",
                        "đánh giá đề tài",
                        "nhận xét cách chọn lọc và sắp xếp thông tin",
                        "đánh giá cách chọn lọc và sắp xếp thông tin",
                        "nhận xét thái độ của người viết",
                        "đánh giá thái độ của người viết",
                        "nhận xét quan điểm của người viết",
                        "đánh giá quan điểm của người viết"
                    ],
                    "Vận dụng": [
                        "vận dụng kiến thức tiếng Việt",
                        "vận dụng kiến thức văn học",
                        "vận dụng kinh nghiệm",
                        "so sánh nhân vật",
                        "so sánh văn bản",
                        "liên hệ văn bản với bản thân",
                        "liên hệ văn bản với bối cảnh",
                        "viết đoạn văn",
                        "viết văn bản",
                        "thuyết trình vấn đề",
                        "thuyết trình ý kiến",
                        "thuyết trình bài giới thiệu",
                        "thuyết trình báo cáo nghiên cứu",
                        "trình bày vấn đề",
                        "trình bày ý kiến",
                        "trình bày bài giới thiệu",
                        "trình bày báo cáo nghiên cứu"
                    ]
                },
                "Toán": {
                    "Biết": [
                        "đọc",
                        "đếm",
                        "viết",
                        "làm quen",
                        "nhận dạng",
                        "nhận biết"
                    ],
                    "Hiểu": [
                        "mô tả",
                        "giải thích",
                        "thể hiện",
                        "sắp xếp"
                    ],
                    "Vận dụng": [
                        "tính",
                        "vẽ",
                        "thực hiện",
                        "sử dụng",
                        "vận dụng",
                        "so sánh",
                        "phân biệt",
                        "lí giải",
                        "chứng minh",
                        "giải quyết"
                    ]
                },
                "Tin học": {
                    "Biết": [
                        "kể lại được điều quan sát",
                        "kể lại được điều biết thêm",
                        "nêu được công việc",
                        "nêu được ví dụ",
                        "nêu được tên thiết bị",
                        "nêu được tên nghề",
                        "nêu được tên thành phần",
                        "nêu được tên và độ lớn đơn vị đo dung lượng",
                        "nêu được vai trò",
                        "nêu được lợi ích",
                        "nêu được khả năng",
                        "nêu được khái niệm",
                        "nêu được thông tin chính",
                        "nêu được công dụng",
                        "nêu được ưu điểm",
                        "nêu được nhược điểm",
                        "nêu được tác hại",
                        "nêu được nhu cầu",
                        "nêu được chức năng",
                        "nêu được ý nghĩa",
                        "nêu được đặc điểm",
                        "nêu được nội dung liên quan đến Luật Công nghệ thông tin",
                        "nêu được hành vi vi phạm pháp luật",
                        "nêu được các bước",
                        "nêu được quy trình",
                        "nêu được dịch vụ",
                        "nêu được cách",
                        "nêu được dạng lừa đảo phổ biến trên mạng",
                        "nêu được cảnh báo",
                        "nêu được mục tiêu và thành tựu",
                        "nêu được trải nghiệm của bản thân",
                        "nêu được lĩnh vực sử dụng kĩ thuật mô phỏng",
                        "nêu được ý tưởng của kĩ thuật",
                        "nêu được ứng dụng của đường truyền",
                        "nêu được ứng dụng của kiểu dữ liệu tuyến tính",
                        "nêu được ứng dụng của Duyệt đồ thị",
                        "nêu được tình huống dẫn đến mất dữ liệu",
                        "nêu được tình huống phải cài đặt phần mềm",
                        "khởi động được máy tính",
                        "khởi động được một số thiết bị thông dụng",
                        "kích hoạt được phần mềm",
                        "biết được không phải thông tin nào trên Internet cũng phù hợp với lứa tuổi",
                        "biết được tác hại của bệnh nghiện Internet",
                        "biết được người xấu có thể lợi dụng",
                        "biết được thông tin cá nhân có thể được lưu trữ",
                        "biết được có thể biểu diễn sắp xếp phân loại",
                        "biết được chức năng của thiết bị",
                        "biết được cách kết nối các bộ phận",
                        "biết được cách kết nối PC với thiết bị",
                        "biết được bit là đơn vị nhỏ nhất",
                        "biết được chương trình máy tính là một mô tả thuật toán",
                        "biết được tệp chương trình cũng là dữ liệu",
                        "biết được việc kiểm thử chương trình giúp phát hiện lỗi",
                        "biết được khả năng đính kèm",
                        "biết được vai trò của máy tính",
                        "biết được tính ưu việt của việc sử dụng máy tính",
                        "nhận biết được cái gì là thông tin và đâu là quyết định",
                        "nhận biết được ba dạng thông tin hay gặp",
                        "nhận biết được màn hình cảm biến",
                        "nhận biết được tệp",
                        "nhận biết được được thư mục",
                        "nhận biết được ổ đĩa",
                        "nhận biết được nhu cầu lưu trữ dữ liệu",
                        "nhận biết được biểu tượng của phần mềm",
                        "nhận biết được mục đích chia một nhiệm vụ lớn thành các nhiệm vụ nhỏ hơn",
                        "nhận biết được sự khác nhau giữa thông tin và dữ liệu",
                        "nhận biết được sự có mặt của các thiết bị",
                        "nhận biết được thiết bị số thông dụng",
                        "nhận biết được sơ đồ mạch logic",
                        "nhận biết được mạng xã hội",
                        "nhận biết được sự mô phỏng thế giới thực",
                        "nhận biết được đặc trưng cơ bản của nhóm nghề",
                        "nhận biết được lợi ích của phương pháp làm mịn dần",
                        "nhận biết được tính ưu việt của kĩ thuật đệ quy",
                        "nhận thấy được phần mềm có thể giúp tập gõ bàn phím",
                        "biết cách được dùng máy tìm kiếm",
                        "biết cách được đăng kí tài khoản thư điện tử",
                        "nhận ra được thông tin thu nhận và được xử lí là gì",
                        "nhận ra được chương trình máy tính",
                        "nhận ra được thiết bị vào – ra",
                        "nhận diện được hình dạng các bộ phận chính",
                        "nhận diện được một số thông điệp lừa đảo trên mạng",
                        "chỉ ra được khu vực chính của bàn phím",
                        "chỉ ra được lĩnh vực phát triển mạnh mẽ dựa trên AI",
                        "thực hiện được các thao tác",
                        "thực hiện được quyền sở hữu trí tuệ ở mức đơn giản",
                        "thực hiện được tạo thư mục",
                        "thực hiện được tìm kiếm thông tin",
                        "thực hiện được ra khỏi phần mềm",
                        "thực hiện được định dạng",
                        "thực hiện được các phép tính cơ bản AND OR NOT",
                        "thực hiện được chương trình",
                        "thực hiện được chỉ dẫn trong tài liệu",
                        "thực hiện được tạo lập cơ sở dữ liệu",
                        "thực hiện được cập nhật cơ sở dữ liệu",
                        "thực hiện được một số chức năng trong phần mềm",
                        "tìm kiếm được thông tin"
                    ],
                    "Hiểu": [
                        "diễn tả được khái niệm thuật toán",
                        "diễn đạt được một số khái niệm trong chủ đề cơ sở dữ liệu",
                        "mô tả được chức năng của các bộ phận",
                        "mô tả được dữ liệu thống kê",
                        "mô tả được khái niệm kiểu dữ liệu tuyến tính",
                        "mô tả được thuật toán",
                        "mô tả được kịch bản",
                        "mô tả được giải pháp",
                        "trình bày được tác dụng của một số công cụ",
                        "trình bày được thông tin ở dạng bảng",
                        "trình bày được ý tưởng dưới dạng sơ đồ tư duy",
                        "trình bày được khái niệm",
                        "trình bày được tầm quan trọng",
                        "trình bày được lịch sử máy tính",
                        "trình bày được vấn đề bình đẳng giới",
                        "trình bày được tác động tiêu cực",
                        "trình bày được quá trình giải quyết vấn đề",
                        "trình bày được công việc đặc thù và sản phẩm chính",
                        "trình bày được thông tin hướng nghiệp",
                        "trình bày được những đóng góp cơ bản",
                        "trình bày được những thay đổi",
                        "trình bày được phương thức học tập và làm việc",
                        "trình bày được cách đề phòng",
                        "trình bày được lịch sử của hệ điều hành",
                        "trình bày được cấu trúc dữ liệu",
                        "trình bày được vai trò và cơ chế hoạt động",
                        "trình bày được tính đệ quy",
                        "trình bày được ý tưởng của kĩ thuật duyệt",
                        "phát biểu được nhiệm vụ đặt ra",
                        "phát biểu được bài toán sắp xếp và tìm kiếm",
                        "nêu được ví dụ minh hoạ",
                        "nêu được nhận xét",
                        "nêu được mối quan hệ",
                        "nêu được vấn đề nảy sinh về đạo đức và pháp luật khi giao tiếp trên mạng",
                        "giải thích được ví dụ minh hoạ",
                        "giải thích được lợi ích",
                        "giải thích được máy tính là công cụ hiệu quả",
                        "giải thích được sự cần thiết",
                        "giải thích được tính chất của thông tin",
                        "giải thích được một số khái niệm",
                        "giải thích được có những bước có thể chuyển giao cho máy tính",
                        "giải thích được chương trình là bản mô tả thuật toán",
                        "giải thích được biểu diễn thông tin chỉ với hai kí hiệu 0 và 1",
                        "giải thích được ứng dụng của hệ nhị phân",
                        "giải thích được vai trò của các mạch logic",
                        "giải thích được việc số hoá văn bản",
                        "giải thích được chức năng của bảng mã",
                        "giải thích được chức năng của hệ điều hành",
                        "giải thích được phần mở rộng của tên tệp",
                        "giải thích được việc đưa các công thức vào bảng tính",
                        "giải thích được sự khác nhau giữa địa chỉ tương đối và địa chỉ tuyệt đối",
                        "giải thích được sự thay đổi địa chỉ tương đối",
                        "giải thích được thuật toán sắp xếp và tìm kiếm",
                        "giải thích được mối liên quan giữa sắp xếp và tìm kiếm",
                        "giải thích được tác hại",
                        "giải thích được sự cần thiết và tầm quan trọng",
                        "giải thích được những biểu hiện",
                        "giải thích được tác động",
                        "giải thích được ý kiến",
                        "giải thích được sự bình đẳng giới trong tin học",
                        "giải thích được vai trò của thiết bị",
                        "giải thích được sự vi phạm bản quyền",
                        "giải thích được nội dung của luật",
                        "giải thích được đơn vị đo hiệu năng",
                        "giải thích được thông số",
                        "giải thích được tính ưu việt",
                        "giải thích được cấu trúc của trang web",
                        "giải thích được kĩ thuật thiết kế thuật toán",
                        "hiểu được chương trình là dãy các lệnh điều khiển máy tính",
                        "tìm hiểu được cấu trúc cây của thư mục",
                        "tìm hiểu được chức năng của hệ quản trị cơ sở dữ liệu",
                        "tìm hiểu được công việc ở một số doanh nghiệp",
                        "tìm hiểu được thông tin ngành đào tạo",
                        "mô phỏng được các phép toán Duyệt cây nhị phân",
                        "mô phỏng được thuật toán tạo Cây tìm kiếm nhị phân",
                        "mô phỏng được thuật toán duyệt Duyệt đồ thị",
                        "biểu diễn được Hàng đợi và Ngăn xếp",
                        "biểu diễn được Cây tìm kiếm nhị phân",
                        "biểu diễn được Đồ thị",
                        "phân tích được thiết bị số khác cũng là hệ thống xử lí thông tin",
                        "phân tích được ưu nhược điểm về giao tiếp trong thế giới ảo",
                        "phân tích được tính nhân văn trong ứng xử",
                        "phân tích được tương quan tuyến tính",
                        "đọc hiểu được chương trình",
                        "đọc hiểu được tài liệu hướng dẫn",
                        "đọc hiểu được công thức trong bảng tính điện tử",
                        "phân biệt được hình dạng",
                        "phân biệt được các loại thông tin",
                        "phân biệt được thông tin với vật mang tin",
                        "phân biệt được hệ điều hành với phần mềm ứng dụng",
                        "phân biệt được thông tin và dữ liệu",
                        "phân biệt được hai loại kiến trúc tập trung và phân tán của hệ Cơ sở dữ liệu",
                        "phân biệt được chức năng",
                        "so sánh được mạng LAN và Internet",
                        "so sánh được phần mềm nguồn mở với phần mềm thương mại",
                        "đánh giá được lợi ích của thông tin"
                    ],
                    "Vận dụng": [
                        "tìm được tệp",
                        "tìm được thông tin",
                        "biên tập được phim",
                        "biên tập được màu sắc ảnh",
                        "cắt được ảnh",
                        "chuẩn bị được báo cáo của dự án",
                        "thể hiện được mong muốn biết sử dụng máy tính",
                        "thể hiện được sự hợp tác của mình",
                        "thể hiện được sự tôn trọng tính riêng tư và bản quyền nội dung thông tin",
                        "biết dùng công cụ gạch đầu dòng",
                        "dùng được địa chỉ trong công thức",
                        "chạy thử được chương trình",
                        "chuyển đổi được giữa các đơn vị lưu trữ thông tin",
                        "cài đặt được phần mềm",
                        "kết nối được PC với các thiết bị số",
                        "chia sẻ được thông tin",
                        "chia sẻ được dữ liệu",
                        "khai thác được thông tin",
                        "khai thác được một số nguồn học liệu mở",
                        "lưu trữ được văn bản",
                        "chỉnh sửa được văn bản",
                        "chỉnh sửa được ảnh",
                        "chỉnh sửa được màu sắc",
                        "tuỳ chỉnh được chức năng của máy tính",
                        "xác lập được các lựa chọn theo tiêu chí tìm kiếm",
                        "định dạng được kí tự",
                        "định dạng được kiểu chữ",
                        "định dạng được màu chữ",
                        "định dạng được kích thước chữ",
                        "lắp ráp được robot giáo dục",
                        "soạn thảo được văn bản",
                        "tạo được tệp",
                        "tạo được chương trình",
                        "tạo được thư viện",
                        "tạo được thư mục",
                        "tạo được sản phẩm số",
                        "xác định được cấu trúc dữ liệu thích hợp",
                        "xác định được chủ đề của thông tin cần tìm",
                        "xác định được phần cơ sở và phần đệ quy trong mô tả đệ quy",
                        "chia được công việc thành những việc nhỏ hơn",
                        "chọn được thông tin phù hợp",
                        "chuẩn bị được báo cáo",
                        "thiết lập được mối quan hệ giữa các bảng",
                        "sử dụng được công cụ tìm kiếm",
                        "sử dụng được biến nhớ và biểu thức",
                        "sử dụng được phần mềm",
                        "vận dụng được quy tắc thực hành",
                        "vận dụng được phương pháp làm mịn dần",
                        "thực hiện được biện pháp bảo vệ dữ liệu",
                        "thực hiện được cài đặt hoặc gỡ bỏ phần mềm",
                        "thực hiện được biện pháp phòng ngừa",
                        "thực hiện được nhiệm vụ giáo viên đặt ra",
                        "thực hiện được giao tiếp qua mạng",
                        "thực hiện được dự án",
                        "thực hiện được khai thác cơ sở dữ liệu",
                        "thực hiện được thao tác xử lí ảnh",
                        "bảo vệ được thông tin",
                        "hợp tác được theo nhóm để viết kịch bản",
                        "kiểm thử được chương trình",
                        "viết được chương trình",
                        "viết được bản hướng dẫn",
                        "thiết kế được các nhân vật hoạt hình",
                        "quản lí được dự án"
                    ]
                },
                "Khoa học": {
                    "Biết": [
                        "nêu được",
                        "kể được",
                        "xác định được"
                    ],
                    "Hiểu": [
                        "mô tả được",
                        "vẽ được",
                        "trình bày được",
                        "nêu được ví dụ",
                        "so sánh được",
                        "phân biệt được"
                    ],
                    "Vận dụng": [
                        "nhận xét được",
                        "đặt được câu hỏi",
                        "giải thích được",
                        "vận dụng được",
                        "thực hiện được",
                        "đưa ra được",
                        "đề xuất được",
                        "xây dựng được"
                    ]
                },
                "Lịch sử và Địa lý": {
                    "Biết": [
                        "kể được tên một số đối tượng địa lí",
                        "kể được tên một số dân tộc",
                        "kể được tên một số sự kiện trong không gian và thời gian cụ thể",
                        "kể được tên một số nhân vật lịch sử trong không gian và thời gian cụ thể",
                        "liệt kê được số lượng đơn vị hành chính",
                        "liệt kê được số dân",
                        "liệt kê được sự kiện",
                        "liệt kê được sự vật",
                        "liệt kê được nhân vật",
                        "ghi lại được các mốc chính của một giai đoạn lịch sử",
                        "ghi lại được các mốc chính của một quá trình lịch sử",
                        "ghi lại được các mốc chính của một nhân vật lịch sử",
                        "kể lại được các mốc chính của một giai đoạn lịch sử",
                        "kể lại được các mốc chính của một quá trình lịch sử",
                        "kể lại được các mốc chính của một nhân vật lịch sử",
                        "xác định được vị trí địa lí của vùng miền",
                        "xác định được vị trí địa lí của quốc gia",
                        "xác định được vị trí địa lí của châu lục",
                        "xác định được vị trí một số đối tượng địa lí trên bản đồ",
                        "xác định được vị trí một số địa điểm lịch sử trên bản đồ",
                        "xác định được vị trí một số đối tượng địa lí trên lược đồ",
                        "xác định được vị trí một số địa điểm lịch sử trên lược đồ",
                        "đặt đúng vị trí đối tượng trên bản đồ",
                        "đặt đúng vị trí đối tượng trên sơ đồ",
                        "điền vào chỗ trống các từ phù hợp",
                        "điền vào chỗ trống các cụm từ phù hợp",
                        "điền vào ô trống các từ phù hợp",
                        "điền vào ô trống các cụm từ phù hợp",
                        "nối các đường còn thiếu trong sơ đồ",
                        "nối cặp các từ có quan hệ logic nào đó",
                        "tìm kiếm thông tin nguồn sử liệu",
                        "tìm kiếm thông tin hình ảnh",
                        "tìm kiếm thông tin sự kiện",
                        "tìm kiếm thông tin vấn đề lịch sử",
                        "tìm kiếm một số đối tượng địa lí",
                        "tìm kiếm đường đi trên bản đồ"
                    ],
                    "Hiểu": [
                        "trình bày được đặc điểm cơ bản của đối tượng địa lí",
                        "trình bày được sự phân bố đối tượng địa lí",
                        "trình bày được diễn trình của các sự kiện lịch sử",
                        "trình bày được diễn trình của nhân vật lịch sử",
                        "trình bày được diễn trình của quá trình lịch sử",
                        "mô tả được đặc điểm cơ bản của địa hình",
                        "mô tả được đặc điểm cơ bản của khí hậu",
                        "mô tả được đặc điểm cơ bản của sông ngòi",
                        "mô tả được một số nét văn hoá",
                        "mô tả được hoạt động sản xuất",
                        "mô tả được một số nét cơ bản về sự kiện lịch sử",
                        "mô tả được một số nét cơ bản về nhân vật lịch sử",
                        "mô tả được một số nét cơ bản về di tích lịch sử",
                        "mô tả được một số nét cơ bản về lễ hội",
                        "vẽ được đường thời gian",
                        "xây dựng được sơ đồ tiến trình lịch sử",
                        "xây dựng được sơ đồ diễn biến chính của một số cuộc khởi nghĩa",
                        "xây dựng được sơ đồ diễn biến chính của trận đánh lớn",
                        "sử dụng bản đồ nêu được một số thông tin địa lí",
                        "sử dụng lược đồ nêu được một số thông tin địa lí",
                        "sử dụng các thông tin trên biểu đồ nêu được một số thông tin địa lí",
                        "sử dụng bản đồ nêu được sự kiện lịch sử",
                        "sử dụng lược đồ nêu được sự kiện lịch sử",
                        "sử dụng các thông tin trên biểu đồ nêu được sự kiện lịch sử",
                        "trình bày được ảnh hưởng của vị trí địa lí",
                        "trình bày được ảnh hưởng của đặc điểm tự nhiên",
                        "trình bày được sự thích ứng của con người với thiên nhiên",
                        "trình bày được một số khó khăn do thiên nhiên gây ra",
                        "trình bày được ý nghĩa của một sự kiện lịch sử",
                        "trình bày được ý nghĩa của một hiện tượng lịch sử",
                        "trình bày được ý nghĩa của một hiện tượng địa lí",
                        "trình bày được mối quan hệ giữa các sự kiện lịch sử",
                        "trình bày được mối quan hệ giữa các hiện tượng địa lí",
                        "phân biệt được các dạng địa hình",
                        "phân biệt được phương thức khai thác tự nhiên",
                        "phân biệt được đặc điểm tự nhiên của các châu lục",
                        "so sánh được đặc điểm khí hậu của hai địa điểm",
                        "so sánh được phân bố dân cư của hai vùng",
                        "nêu được tác động của tự nhiên đến sản xuất",
                        "nêu được tác động của tự nhiên đến đời sống của con người",
                        "nêu được ý nghĩa của sự kiện lịch sử",
                        "nêu được vai trò của một nhân vật lịch sử",
                        "nêu được nhận xét của cá nhân về các sự kiện lịch sử trên cơ sở nhận thức và tư duy lịch sử",
                        "nêu được nhận xét của cá nhân về nhân vật lịch sử trên cơ sở nhận thức và tư duy lịch sử",
                        "nêu được nhận xét của cá nhân về quá trình lịch sử trên cơ sở nhận thức và tư duy lịch sử"
                    ],
                    "Vận dụng": [
                        "xác định được phương hướng ngoài thực địa",
                        "xác định được vị trí của một địa điểm",
                        "xác định được phạm vi không gian trên bản đồ",
                        "xác định được phạm vi không gian trên lược đồ",
                        "tìm hiểu được một hiện tượng địa lí thông qua tài liệu",
                        "tìm hiểu được một hiện tượng địa lí thông qua tham quan",
                        "tìm hiểu được một hiện tượng địa lí thông qua khảo sát",
                        "tìm hiểu được một hiện tượng lịch sử thông qua tài liệu",
                        "tìm hiểu được một hiện tượng lịch sử thông qua tham quan",
                        "tìm hiểu được một hiện tượng lịch sử thông qua khảo sát",
                        "khám phá được một hiện tượng địa lí thông qua tài liệu",
                        "khám phá được một hiện tượng địa lí thông qua tham quan",
                        "khám phá được một hiện tượng địa lí thông qua khảo sát",
                        "khám phá được một hiện tượng lịch sử thông qua tài liệu",
                        "khám phá được một hiện tượng lịch sử thông qua tham quan",
                        "khám phá được một hiện tượng lịch sử thông qua khảo sát",
                        "đặt được câu hỏi về một vấn đề",
                        "liên hệ được thực tế địa phương",
                        "đưa ra được một số biện pháp phòng tránh thiên tai ở một vùng cụ thể",
                        "đưa ra được một số biện pháp bảo vệ tài nguyên thiên nhiên ở một vùng cụ thể",
                        "vận dụng được điều đã học vào trường hợp cụ thể",
                        "vận dụng được điều đã học vào hoàn cảnh cụ thể",
                        "đề xuất được ở mức độ đơn giản giải pháp",
                        "thực hiện được hành động chia sẻ với người dân vùng thiên tai",
                        "vẽ được bức tranh thể hiện một thế giới trong tương lai",
                        "vẽ được bức tranh thể hiện sự quan tâm đến môi trường",
                        "sơ đồ hoá một hiện tượng",
                        "sơ đồ hoá một quá trình",
                        "sơ đồ hoá một mối quan hệ nhân quả",
                        "trình bày được kết quả làm việc cá nhân về một vấn đề lịch sử",
                        "trình bày được kết quả làm việc cá nhân về một vấn đề địa lí",
                        "trình bày được kết quả làm việc nhóm về một vấn đề lịch sử",
                        "trình bày được kết quả làm việc nhóm về một vấn đề địa lí"
                    ]
                },
                "Tiếng Anh": {
                    "Biết": [
                        "nghe hiểu được các từ và cụm từ quen thuộc",
                        "nghe hiểu được các chỉ dẫn rất đơn giản",
                        "nghe và trả lời được các câu hỏi rất đơn giản",
                        "nghe hiểu được các đoạn hội thoại ngắn",
                        "nói được các từ và cụm từ quen thuộc",
                        "hỏi và trả lời được các câu hỏi đơn giản",
                        "đọc đúng được chữ cái",
                        "đọc hiểu được các từ và cụm từ quen thuộc",
                        "đọc hiểu được các câu ngắn",
                        "đọc hiểu được các văn bản ngắn",
                        "viết được các từ và cụm từ rất đơn giản",
                        "điền được thông tin cá nhân vào mẫu đơn giản",
                        "nhận biết được trọng âm từ",
                        "nhận biết được nhịp điệu và ngữ điệu",
                        "nhận biết được từ vựng theo chủ đề",
                        "biết được các cấu trúc quen thuộc",
                        "biết được các mẫu câu đơn giản",
                        "biết được các thì cơ bản",
                        "biết được câu hỏi nghi vấn",
                        "biết được câu mệnh lệnh",
                        "biết được đại từ nhân xưng",
                        "biết được tính từ sở hữu",
                        "biết được giới từ chỉ địa điểm",
                        "biết được liên từ cơ bản",
                        "nêu được thông tin về bản thân",
                        "nêu được thông tin về gia đình",
                        "nêu được thông tin về trường học",
                        "nêu được sở thích",
                        "nêu được nghề nghiệp",
                        "nêu được màu sắc",
                        "nêu được con vật",
                        "nêu được thời tiết",
                        "nêu được phương tiện giao thông",
                        "thực hiện được các chỉ dẫn đơn giản trong lớp học"
                    ],
                    "Hiểu": [
                        "hiểu được nội dung chính của câu chuyện ngắn",
                        "hiểu được các đoạn hội thoại đơn giản",
                        "hiểu được các văn bản ngắn theo chủ đề quen thuộc",
                        "mô tả được bản thân và người khác",
                        "mô tả được hoạt động hằng ngày",
                        "mô tả được trường học và gia đình",
                        "trình bày được sở thích",
                        "trình bày được thói quen",
                        "trình bày được hoạt động học tập",
                        "trình bày được hoạt động ngoại khóa",
                        "trình bày được nghề nghiệp",
                        "trình bày được thời tiết",
                        "trình bày được sức khỏe",
                        "giải thích được thông tin đơn giản",
                        "giải thích được ý nghĩa của từ và cụm từ quen thuộc",
                        "giải thích được nội dung cơ bản của đoạn văn",
                        "phân biệt được các loại câu cơ bản",
                        "phân biệt được thì hiện tại đơn và hiện tại tiếp diễn",
                        "phân biệt được thì quá khứ đơn",
                        "phân biệt được thì tương lai đơn",
                        "so sánh được người, vật hoặc sự việc đơn giản",
                        "đọc hiểu được các thông điệp ngắn",
                        "đọc hiểu được hướng dẫn đơn giản",
                        "đọc hiểu được các đoạn văn khoảng 30 - 80 từ",
                        "đọc hiểu được nội dung theo chủ đề quen thuộc",
                        "hỏi và trả lời được về các chủ đề quen thuộc",
                        "diễn đạt được nhu cầu giao tiếp cơ bản",
                        "trả lời được câu hỏi trực tiếp trong giao tiếp đơn giản",
                        "sử dụng được các mẫu câu giao tiếp quen thuộc",
                        "vận dụng được từ vựng theo chủ đề",
                        "vận dụng được cấu trúc câu đơn giản trong giao tiếp"
                    ],
                    "Vận dụng": [
                        "sử dụng được tiếng Anh trong giao tiếp đơn giản",
                        "sử dụng được từ và cụm từ theo chủ đề",
                        "sử dụng được câu đơn trong giao tiếp",
                        "sử dụng được các thì cơ bản",
                        "sử dụng được câu hỏi có từ để hỏi",
                        "sử dụng được câu hỏi nghi vấn",
                        "sử dụng được động từ tình thái",
                        "sử dụng được giới từ",
                        "sử dụng được liên từ",
                        "thực hiện được hội thoại đơn giản",
                        "thực hiện được giao tiếp hằng ngày",
                        "thực hiện được các yêu cầu và chỉ dẫn bằng tiếng Anh",
                        "viết được câu đơn giản",
                        "viết được đoạn văn ngắn",
                        "viết được đoạn văn khoảng 10 - 40 từ",
                        "viết được tin nhắn đơn giản",
                        "viết được biểu mẫu đơn giản",
                        "viết được thông tin cá nhân",
                        "trình bày được chủ đề quen thuộc bằng tiếng Anh",
                        "nói được về bản thân",
                        "nói được về gia đình",
                        "nói được về trường học",
                        "nói được về bạn bè",
                        "nói được về sở thích",
                        "nói được về nghề nghiệp",
                        "nói được về thời tiết",
                        "trao đổi được thông tin đơn giản",
                        "tham gia được hội thoại ngắn",
                        "đọc được văn bản ngắn phục vụ học tập",
                        "khai thác được thông tin từ đoạn văn ngắn",
                        "hoàn thành được nhiệm vụ học tập bằng tiếng Anh"
                    ]
                },
                "Công nghệ": {
                    "Biết": [
                        "kể tên",
                        "liệt kê",
                        "trình bày",
                        "nhận biết",
                        "nhận ra",
                        "phát hiện",
                        "tìm kiếm",
                        "nêu",
                        "mô tả",
                        "ghi nhớ"
                    ],
                    "Hiểu": [
                        "phân biệt",
                        "tính toán",
                        "vẽ",
                        "so sánh",
                        "phân tích",
                        "giải thích",
                        "đọc",
                        "tóm tắt",
                        "trao đổi",
                        "làm rõ",
                        "đánh giá",
                        "biểu diễn",
                        "thao tác",
                        "bảo quản",
                        "sử dụng",
                        "khắc phục",
                        "liên hệ",
                        "nhận định",
                        "lựa chọn",
                        "nhận thức",
                        "xác định"
                    ],
                    "Vận dụng": [
                        "khai thác",
                        "tạo lập",
                        "vận hành",
                        "xác định thông số",
                        "chăm sóc",
                        "bảo dưỡng",
                        "đề xuất",
                        "thử nghiệm",
                        "điều chỉnh",
                        "lập kế hoạch",
                        "chế tạo",
                        "kiểm tra",
                        "thử nghiệm",
                        "hoàn thiện",
                        "thiết kế",
                        "phác thảo",
                        "thực hiện",
                        "lắp ráp"
                    ]
                },
                "Âm nhạc": {
                    "Biết": [
                        "gọi được tên hình thức biểu diễn",
                        "kể được tên một số nhạc sĩ tiêu biểu",
                        "liệt kê được một số loại nhạc cụ",
                        "nhắc lại được nội dung bài hát",
                        "phát biểu được lời ca",
                        "thuộc lời ca",
                        "nhận biết các nốt nhạc",
                        "nhận biết các kí hiệu ghi nhạc"
                        "xác định được cao độ các nốt nhạc",
                        "xác định được trường độ các nốt nhạc",
                        "đọc đúng cao độ các nốt nhạc",
                        "đọc đúng trường độ các nốt nhạc"
                    ],
                    "Hiểu": [
                        "mô tả được động tác chơi nhạc cụ",
                        "nêu được ví dụ",
                        "tóm tắt được ý nghĩa của một số kí hiệu âm nhạc",
                        "tóm tắt được ý nghĩa của một số thuật ngữ âm nhạc",
                        "giải thích được ý nghĩa của một số kí hiệu âm nhạc",
                        "giải thích được ý nghĩa của một số thuật ngữ âm nhạc",
                        "so sánh được sự khác nhau giữa các loại nhịp"
                    ],
                    "Vận dụng": [
                        "biểu diễn được các tiết mục âm nhạc",
                        "điều chỉnh được giọng hát để tạo nên sự hài hoà",
                        "tổ chức được hoạt động âm nhạc phù hợp với lứa tuổi",
                        "xếp loại được kĩ năng thể hiện âm nhạc của bản thân",
                        "xếp loại được kĩ năng thể hiện âm nhạc của người khác",
                        "đánh giá được kĩ năng thể hiện âm nhạc của bản thân",
                        "đánh giá được kĩ năng thể hiện âm nhạc của người khác"
                    ]
                },
                "Mĩ thuật": {
                    "Biết": [
                        "nhận biết được yếu tố tạo hình",
                        "nhận biết được nguyên lí tạo hình",
                        "nhận biết được đặc điểm",
                        "đọc được tên màu sắc",
                        "đọc được tên tác giả",
                        "đọc được tên sản phẩm",
                        "đọc được tên tác phẩm",
                        "đọc được tên trường phái",
                        "liệt kê được đồ dùng",
                        "liệt kê được công cụ",
                        "liệt kê được vật liệu",
                        "liệt kê được ngành nghề",
                        "nêu được yếu tố đặc trưng",
                        "nêu được ý tưởng",
                        "nêu được giải pháp",
                        "xác định được chủ đề",
                        "xác định được mục đích",
                        "xác định được đối tượng"
                    ],
                    "Hiểu": [
                        "trình bày được cảm nhận",
                        "trình bày được sự liên hệ",
                        "trình bày được quan điểm",
                        "biểu đạt được cảm xúc",
                        "biểu đạt được ý tưởng",
                        "biểu đạt được nội dung",
                        "giới thiệu được tác giả",
                        "giới thiệu được sản phẩm",
                        "giới thiệu được tác phẩm",
                        "tóm tắt được giá trị nghệ thuật",
                        "tóm tắt được cuộc đời",
                        "tóm tắt được sự nghiệp",
                        "giải thích được sắp xếp bố cục",
                        "giải thích được tính phổ biến",
                        "giải thích được địa điểm",
                        "phân tích được vẻ đẹp",
                        "phân tích được mối quan hệ giữa tính thẩm mĩ và tính ứng dụng",
                        "phân tích được nhu cầu xã hội",
                        "phân loại được thể loại",
                        "phân loại được hình thức",
                        "phân biệt được tranh vẽ",
                        "phân biệt được tranh in",
                        "phân biệt được một số chất liệu",
                        "đánh giá được sản phẩm",
                        "đánh giá được hoạt động thực hành",
                        "đánh giá được thảo luận",
                        "đánh giá được mối quan hệ giữa tính thẩm mĩ và tính ứng dụng",
                        "nhận định được giá trị thẩm mĩ",
                        "nhận định được tiến trình phát triển",
                        "nhận định được sự tác động của internet"
                    ],
                    "Vận dụng": [
                        "mô phỏng được đối tượng thẩm mĩ",
                        "phác thảo được ý tưởng",
                        "lựa chọn được công cụ",
                        "lựa chọn được vật liệu",
                        "lựa chọn được chất liệu",
                        "lựa chọn được hình thức thực hành",
                        "lựa chọn được vị trí trưng bày",
                        "sử dụng được vật liệu",
                        "sử dụng được công cụ",
                        "sử dụng được phương tiện",
                        "thực hiện được thao tác",
                        "thực hiện được các bước thực hành",
                        "thực hiện được phác thảo",
                        "vận dụng được yếu tố tạo hình",
                        "vận dụng được nguyên lí tạo hình",
                        "vận dụng được yếu tố văn hóa nghệ thuật",
                        "vận dụng được nhịp điệu của hoa văn",
                        "phối hợp được kĩ năng",
                        "phối hợp được vật liệu",
                        "phối hợp được công cụ",
                        "phối hợp được phương tiện",
                        "thể hiện được ý tưởng",
                        "thể hiện được đặc trưng",
                        "thể hiện được cấu trúc",
                        "thể hiện được mục đích",
                        "tạo được sản phẩm",
                        "tạo được sự hài hòa",
                        "tạo được hòa sắc"
                    ]
                },
                "Giáo dục công dân": {
                    "Biết": [
                        "phát biểu được khái niệm",
                        "phát biểu được ý nghĩa một số chuẩn mực hành vi đạo đức",
                        "phát biểu được ý nghĩa một số chuẩn mực hành vi pháp luật",
                        "nêu được khái niệm",
                        "nêu được ý nghĩa một số chuẩn mực hành vi đạo đức",
                        "nêu được ý nghĩa một số chuẩn mực hành vi pháp luật",
                        "nêu được biểu hiện của chuẩn mực hành vi đạo đức",
                        "nêu được biểu hiện của chuẩn mực hành vi pháp luật",
                        "nêu được cách thể hiện cảm xúc",
                        "nêu được thái độ",
                        "nêu được vai trò của tiền",
                        "nêu được cách sử dụng tiền",
                        "nêu được các tình huống cần tìm kiếm sự hỗ trợ",
                        "nêu được các quy định của pháp luật",
                        "liệt kê được biểu hiện của chuẩn mực hành vi đạo đức",
                        "liệt kê được biểu hiện của chuẩn mực hành vi pháp luật",
                        "liệt kê được cách thể hiện cảm xúc",
                        "liệt kê được thái độ",
                        "liệt kê được vai trò của tiền",
                        "liệt kê được cách sử dụng tiền",
                        "liệt kê được các tình huống cần tìm kiếm sự hỗ trợ",
                        "liệt kê được các quy định của pháp luật",
                        "kể ra được biểu hiện của chuẩn mực hành vi đạo đức",
                        "kể ra được biểu hiện của chuẩn mực hành vi pháp luật",
                        "kể ra được cách thể hiện cảm xúc",
                        "kể ra được thái độ",
                        "kể ra được vai trò của tiền",
                        "kể ra được cách sử dụng tiền",
                        "kể ra được các tình huống cần tìm kiếm sự hỗ trợ",
                        "kể ra được các quy định của pháp luật",
                        "nhắc lại được biểu hiện của chuẩn mực hành vi đạo đức",
                        "nhắc lại được biểu hiện của chuẩn mực hành vi pháp luật",
                        "nhắc lại được cách thể hiện cảm xúc",
                        "nhắc lại được thái độ",
                        "nhắc lại được vai trò của tiền",
                        "nhắc lại được cách sử dụng tiền",
                        "nhắc lại được các tình huống cần tìm kiếm sự hỗ trợ",
                        "nhắc lại được các quy định của pháp luật",
                        "nhận biết được sự cần thiết phải thực hiện chuẩn mực hành vi đạo đức",
                        "nhận biết được sự cần thiết phải thực hiện chuẩn mực hành vi pháp luật",
                        "nhận biết được hậu quả của các tình huống nguy hiểm",
                        "nhận biết được hậu quả của các tình huống không an toàn",
                        "phân biệt được thái độ phù hợp với chuẩn mực đạo đức",
                        "phân biệt được hành vi phù hợp với chuẩn mực đạo đức",
                        "phân biệt được thái độ phù hợp với chuẩn mực pháp luật",
                        "phân biệt được hành vi phù hợp với chuẩn mực pháp luật",
                        "phân biệt được thái độ vi phạm chuẩn mực đạo đức",
                        "phân biệt được hành vi vi phạm chuẩn mực đạo đức",
                        "phân biệt được thái độ vi phạm chuẩn mực pháp luật",
                        "phân biệt được hành vi vi phạm chuẩn mực pháp luật",
                        "phân biệt được tăng trưởng kinh tế và phát triển kinh tế",
                        "thu thập được thông tin về các hành vi trong đời sống hằng ngày",
                        "thu thập được thông tin về các nhân vật trong đời sống hằng ngày",
                        "thu thập được thông tin về các sự kiện trong đời sống hằng ngày",
                        "thu thập được thông tin về các tình huống trong đời sống hằng ngày",
                        "thu thập được thông tin về các hành vi trong sách",
                        "thu thập được thông tin về các nhân vật trong sách",
                        "thu thập được thông tin về các sự kiện trong sách",
                        "thu thập được thông tin về các tình huống trong sách",
                        "thu thập được thông tin về các hành vi trên báo",
                        "thu thập được thông tin về các nhân vật trên báo",
                        "thu thập được thông tin về các sự kiện trên báo",
                        "thu thập được thông tin về các tình huống trên báo",
                        "thu thập được thông tin về các hành vi trên mạng Internet",
                        "thu thập được thông tin về các nhân vật trên mạng Internet",
                        "thu thập được thông tin về các sự kiện trên mạng Internet",
                        "thu thập được thông tin về các tình huống trên mạng Internet",
                        "trích dẫn được thông tin về các hành vi trong đời sống hằng ngày",
                        "trích dẫn được thông tin về các nhân vật trong đời sống hằng ngày",
                        "trích dẫn được thông tin về các sự kiện trong đời sống hằng ngày",
                        "trích dẫn được thông tin về các tình huống trong đời sống hằng ngày",
                        "trích dẫn được thông tin về các hành vi trong sách",
                        "trích dẫn được thông tin về các nhân vật trong sách",
                        "trích dẫn được thông tin về các sự kiện trong sách",
                        "trích dẫn được thông tin về các tình huống trong sách",
                        "trích dẫn được thông tin về các hành vi trên báo",
                        "trích dẫn được thông tin về các nhân vật trên báo",
                        "trích dẫn được thông tin về các sự kiện trên báo",
                        "trích dẫn được thông tin về các tình huống trên báo",
                        "trích dẫn được thông tin về các hành vi trên mạng Internet",
                        "trích dẫn được thông tin về các nhân vật trên mạng Internet",
                        "trích dẫn được thông tin về các sự kiện trên mạng Internet",
                        "trích dẫn được thông tin về các tình huống trên mạng Internet",
                        "tìm được thông tin về các hành vi trong đời sống hằng ngày",
                        "tìm được thông tin về các nhân vật trong đời sống hằng ngày",
                        "tìm được thông tin về các sự kiện trong đời sống hằng ngày",
                        "tìm được thông tin về các tình huống trong đời sống hằng ngày",
                        "tìm được thông tin về các hành vi trong sách",
                        "tìm được thông tin về các nhân vật trong sách",
                        "tìm được thông tin về các sự kiện trong sách",
                        "tìm được thông tin về các tình huống trong sách",
                        "tìm được thông tin về các hành vi trên báo",
                        "tìm được thông tin về các nhân vật trên báo",
                        "tìm được thông tin về các sự kiện trên báo",
                        "tìm được thông tin về các tình huống trên báo",
                        "tìm được thông tin về các hành vi trên mạng Internet",
                        "tìm được thông tin về các nhân vật trên mạng Internet",
                        "tìm được thông tin về các sự kiện trên mạng Internet",
                        "tìm được thông tin về các tình huống trên mạng Internet"
                    ],
                    "Hiểu": [
                        "trình bày được hậu quả của lạm phát",
                        "trình bày được hậu quả của thất nghiệp",
                        "trình bày được một số nét trong văn hoá tiêu dùng Việt Nam",
                        "trình bày được kế hoạch kinh doanh của bản thân",
                        "mô tả được hậu quả của lạm phát",
                        "mô tả được hậu quả của thất nghiệp",
                        "mô tả được một số nét trong văn hoá tiêu dùng Việt Nam",
                        "mô tả được kế hoạch kinh doanh của bản thân",
                        "giải thích được ý nghĩa của việc thực hiện chuẩn mực hành vi đạo đức",
                        "giải thích được ý nghĩa của việc thực hiện chuẩn mực hành vi pháp luật",
                        "giải thích được sự cần thiết của việc thực hiện chuẩn mực hành vi đạo đức",
                        "giải thích được sự cần thiết của việc thực hiện chuẩn mực hành vi pháp luật",
                        "giải thích được nguyên nhân dẫn đến cạnh tranh",
                        "giải thích được tính hai mặt của cạnh tranh trong nền kinh tế",
                        "giải thích được nguyên nhân của lạm phát",
                        "giải thích được nguyên nhân của thất nghiệp",
                        "giải thích được vai trò của tăng trưởng kinh tế",
                        "giải thích được vai trò của phát triển kinh tế",
                        "giải thích được sự cần thiết phải giải quyết các vấn đề tác động của phát triển kinh tế đến môi trường tự nhiên",
                        "giải thích được sự cần thiết phải hội nhập kinh tế quốc tế",
                        "diễn giải được ý nghĩa của việc thực hiện chuẩn mực hành vi đạo đức",
                        "diễn giải được ý nghĩa của việc thực hiện chuẩn mực hành vi pháp luật",
                        "diễn giải được sự cần thiết của việc thực hiện chuẩn mực hành vi đạo đức",
                        "diễn giải được sự cần thiết của việc thực hiện chuẩn mực hành vi pháp luật",
                        "diễn giải được nguyên nhân dẫn đến cạnh tranh",
                        "diễn giải được tính hai mặt của cạnh tranh trong nền kinh tế",
                        "diễn giải được nguyên nhân của lạm phát",
                        "diễn giải được nguyên nhân của thất nghiệp",
                        "diễn giải được vai trò của tăng trưởng kinh tế",
                        "diễn giải được vai trò của phát triển kinh tế",
                        "diễn giải được sự cần thiết phải giải quyết các vấn đề tác động của phát triển kinh tế đến môi trường tự nhiên",
                        "diễn giải được sự cần thiết phải hội nhập kinh tế quốc tế",
                        "phân tích được một số tình huống đơn giản trong đời sống về thực hiện pháp luật",
                        "phân tích được một số tình huống đơn giản trong đời sống về vi phạm pháp luật",
                        "phân tích được một số tình huống đơn giản trong đời sống về trách nhiệm pháp lí",
                        "phân tích được bài học thành công trong quá trình kinh doanh của một doanh nghiệp nhỏ cụ thể",
                        "phân tích được bài học thất bại trong quá trình kinh doanh của một doanh nghiệp nhỏ cụ thể",
                        "phân tích được những nỗ lực của chính quyền nhằm giải quyết vấn đề môi trường phát sinh do tác động của đô thị hoá và phát triển kinh tế",
                        "phân tích được những nỗ lực của người dân nhằm giải quyết vấn đề môi trường phát sinh do tác động của đô thị hoá và phát triển kinh tế",
                        "lí giải được một số tình huống đơn giản trong đời sống về thực hiện pháp luật",
                        "lí giải được một số tình huống đơn giản trong đời sống về vi phạm pháp luật",
                        "lí giải được một số tình huống đơn giản trong đời sống về trách nhiệm pháp lí",
                        "lí giải được bài học thành công trong quá trình kinh doanh của một doanh nghiệp nhỏ cụ thể",
                        "lí giải được bài học thất bại trong quá trình kinh doanh của một doanh nghiệp nhỏ cụ thể",
                        "lí giải được những nỗ lực của chính quyền nhằm giải quyết vấn đề môi trường phát sinh do tác động của đô thị hoá và phát triển kinh tế",
                        "lí giải được những nỗ lực của người dân nhằm giải quyết vấn đề môi trường phát sinh do tác động của đô thị hoá và phát triển kinh tế",
                        "đánh giá được thái độ của bản thân theo chuẩn mực đạo đức",
                        "đánh giá được hành vi của bản thân theo chuẩn mực đạo đức",
                        "đánh giá được thái độ của người khác theo chuẩn mực đạo đức",
                        "đánh giá được hành vi của người khác theo chuẩn mực đạo đức",
                        "đánh giá được thái độ của bản thân theo chuẩn mực pháp luật",
                        "đánh giá được hành vi của bản thân theo chuẩn mực pháp luật",
                        "đánh giá được thái độ của người khác theo chuẩn mực pháp luật",
                        "đánh giá được hành vi của người khác theo chuẩn mực pháp luật",
                        "đánh giá được tác hại của hành vi vi phạm chuẩn mực đạo đức",
                        "đánh giá được tác hại của hành vi vi phạm chuẩn mực pháp luật",
                        "đánh giá được một số vấn đề đơn giản thường gặp về pháp luật",
                        "đánh giá được một số vấn đề đơn giản thường gặp về kinh tế",
                        "đánh giá được một số biện pháp đang áp dụng trong thực tế nhằm giải quyết tác động của phát triển kinh tế đến môi trường tự nhiên",
                        "đánh giá được một số chính sách đang áp dụng trong thực tế nhằm giải quyết tác động của phát triển kinh tế đến môi trường tự nhiên",
                        "nhận xét được thái độ của bản thân theo chuẩn mực đạo đức",
                        "nhận xét được hành vi của bản thân theo chuẩn mực đạo đức",
                        "nhận xét được thái độ của người khác theo chuẩn mực đạo đức",
                        "nhận xét được hành vi của người khác theo chuẩn mực đạo đức",
                        "nhận xét được thái độ của bản thân theo chuẩn mực pháp luật",
                        "nhận xét được hành vi của bản thân theo chuẩn mực pháp luật",
                        "nhận xét được thái độ của người khác theo chuẩn mực pháp luật",
                        "nhận xét được hành vi của người khác theo chuẩn mực pháp luật",
                        "nhận xét được tác hại của hành vi vi phạm chuẩn mực đạo đức",
                        "nhận xét được tác hại của hành vi vi phạm chuẩn mực pháp luật",
                        "nhận xét được một số vấn đề đơn giản thường gặp về pháp luật",
                        "nhận xét được một số vấn đề đơn giản thường gặp về kinh tế",
                        "nhận xét được một số biện pháp đang áp dụng trong thực tế nhằm giải quyết tác động của phát triển kinh tế đến môi trường tự nhiên",
                        "nhận xét được một số chính sách đang áp dụng trong thực tế nhằm giải quyết tác động của phát triển kinh tế đến môi trường tự nhiên"
                    ],
                    "Vận dụng": [
                        "phát hiện được các hiện tượng của đời sống đạo đức",
                        "phát hiện được các sự kiện của đời sống đạo đức",
                        "phát hiện được các tình huống của đời sống đạo đức",
                        "phát hiện được các vấn đề của đời sống đạo đức",
                        "phát hiện được các hiện tượng của đời sống pháp luật",
                        "phát hiện được các sự kiện của đời sống pháp luật",
                        "phát hiện được các tình huống của đời sống pháp luật",
                        "phát hiện được các vấn đề của đời sống pháp luật",
                        "phát hiện được các hiện tượng của đời sống kinh tế",
                        "phát hiện được các sự kiện của đời sống kinh tế",
                        "phát hiện được các tình huống của đời sống kinh tế",
                        "phát hiện được các vấn đề của đời sống kinh tế",
                        "phát hiện được nguyên nhân của những biến động văn hoá do tác động của phát triển kinh tế",
                        "phát hiện được nguyên nhân của những biến động xã hội do tác động của phát triển kinh tế",
                        "chỉ ra được các hiện tượng của đời sống đạo đức",
                        "chỉ ra được các sự kiện của đời sống đạo đức",
                        "chỉ ra được các tình huống của đời sống đạo đức",
                        "chỉ ra được các vấn đề của đời sống đạo đức",
                        "chỉ ra được các hiện tượng của đời sống pháp luật",
                        "chỉ ra được các sự kiện của đời sống pháp luật",
                        "chỉ ra được các tình huống của đời sống pháp luật",
                        "chỉ ra được các vấn đề của đời sống pháp luật",
                        "chỉ ra được các hiện tượng của đời sống kinh tế",
                        "chỉ ra được các sự kiện của đời sống kinh tế",
                        "chỉ ra được các tình huống của đời sống kinh tế",
                        "chỉ ra được các vấn đề của đời sống kinh tế",
                        "chỉ ra được nguyên nhân của những biến động văn hoá do tác động của phát triển kinh tế",
                        "chỉ ra được nguyên nhân của những biến động xã hội do tác động của phát triển kinh tế",
                        "xác định được trách nhiệm của bản thân với tư cách công dân",
                        "xác định được lí tưởng sống của bản thân",
                        "xác định được định hướng nghề nghiệp của bản thân",
                        "thực hiện được hành vi phù hợp chuẩn mực đạo đức",
                        "thực hiện được hành vi phù hợp quy định của pháp luật",
                        "thực hiện được hành vi lành mạnh để tự bảo vệ bản thân",
                        "thực hiện được hành vi tích cực để tự bảo vệ bản thân",
                        "thực hiện được hành vi lành mạnh để phát triển bản thân",
                        "thực hiện được hành vi tích cực để phát triển bản thân",
                        "thực hiện được hành động lành mạnh để tự bảo vệ bản thân",
                        "thực hiện được hành động tích cực để tự bảo vệ bản thân",
                        "thực hiện được hành động lành mạnh để phát triển bản thân",
                        "thực hiện được hành động tích cực để phát triển bản thân",
                        "điều chỉnh được cảm xúc của bản thân phù hợp với chuẩn mực đạo đức",
                        "điều chỉnh được thái độ của bản thân phù hợp với chuẩn mực đạo đức",
                        "điều chỉnh được hành vi của bản thân phù hợp với chuẩn mực đạo đức",
                        "điều chỉnh được thói quen của bản thân phù hợp với chuẩn mực đạo đức",
                        "điều chỉnh được cảm xúc của bản thân phù hợp với pháp luật",
                        "điều chỉnh được thái độ của bản thân phù hợp với pháp luật",
                        "điều chỉnh được hành vi của bản thân phù hợp với pháp luật",
                        "điều chỉnh được thói quen của bản thân phù hợp với pháp luật",
                        "điều chỉnh được cảm xúc của bản thân phù hợp với lứa tuổi",
                        "điều chỉnh được thái độ của bản thân phù hợp với lứa tuổi",
                        "điều chỉnh được hành vi của bản thân phù hợp với lứa tuổi",
                        "điều chỉnh được thói quen của bản thân phù hợp với lứa tuổi",
                        "kiểm soát được cảm xúc của bản thân phù hợp với chuẩn mực đạo đức",
                        "kiểm soát được thái độ của bản thân phù hợp với chuẩn mực đạo đức",
                        "kiểm soát được hành vi của bản thân phù hợp với chuẩn mực đạo đức",
                        "kiểm soát được thói quen của bản thân phù hợp với chuẩn mực đạo đức",
                        "kiểm soát được cảm xúc của bản thân phù hợp với pháp luật",
                        "kiểm soát được thái độ của bản thân phù hợp với pháp luật",
                        "kiểm soát được hành vi của bản thân phù hợp với pháp luật",
                        "kiểm soát được thói quen của bản thân phù hợp với pháp luật",
                        "kiểm soát được cảm xúc của bản thân phù hợp với lứa tuổi",
                        "kiểm soát được thái độ của bản thân phù hợp với lứa tuổi",
                        "kiểm soát được hành vi của bản thân phù hợp với lứa tuổi",
                        "kiểm soát được thói quen của bản thân phù hợp với lứa tuổi",
                        "thích ứng được những thay đổi của cuộc sống",
                        "hình thành được nền nếp sinh hoạt",
                        "đồng tình người khác thực hiện hành vi phù hợp với chuẩn mực đạo đức",
                        "ủng hộ người khác thực hiện hành vi phù hợp với chuẩn mực đạo đức",
                        "nhắc nhở người khác thực hiện hành vi phù hợp với chuẩn mực đạo đức",
                        "khích lệ người khác thực hiện hành vi phù hợp với chuẩn mực đạo đức",
                        "giúp đỡ người khác thực hiện hành vi phù hợp với chuẩn mực đạo đức",
                        "đồng tình người khác thực hiện hành vi phù hợp với pháp luật",
                        "ủng hộ người khác thực hiện hành vi phù hợp với pháp luật",
                        "nhắc nhở người khác thực hiện hành vi phù hợp với pháp luật",
                        "khích lệ người khác thực hiện hành vi phù hợp với pháp luật",
                        "giúp đỡ người khác thực hiện hành vi phù hợp với pháp luật",
                        "không đồng tình những thái độ vi phạm chuẩn mực đạo đức",
                        "không đồng tình những hành vi vi phạm chuẩn mực đạo đức",
                        "phê phán những thái độ vi phạm chuẩn mực đạo đức",
                        "phê phán những hành vi vi phạm chuẩn mực đạo đức",
                        "phản đối những thái độ vi phạm chuẩn mực đạo đức",
                        "phản đối những hành vi vi phạm chuẩn mực đạo đức",
                        "không đồng tình những thái độ vi phạm pháp luật",
                        "không đồng tình những hành vi vi phạm pháp luật",
                        "phê phán những thái độ vi phạm pháp luật",
                        "phê phán những hành vi vi phạm pháp luật",
                        "phản đối những thái độ vi phạm pháp luật",
                        "phản đối những hành vi vi phạm pháp luật",
                        "áp dụng được các nguyên tắc quản lí tiền trong tình huống thực tế",
                        "áp dụng được các phương pháp quản lí tiền trong tình huống thực tế",
                        "áp dụng được biết cách tiết kiệm",
                        "áp dụng được tạo ngân sách cá nhân",
                        "áp dụng được quản lí ngân sách cá nhân",
                        "lập được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "lập được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "lập được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "lập được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "lập được kế hoạch kinh doanh của bản thân",
                        "lập được kế hoạch thu trong gia đình",
                        "lập được kế hoạch chi trong gia đình",
                        "thiết kế được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "thiết kế được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "thiết kế được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "thiết kế được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "thiết kế được kế hoạch kinh doanh của bản thân",
                        "thiết kế được kế hoạch thu trong gia đình",
                        "thiết kế được kế hoạch chi trong gia đình",
                        "xây dựng được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "xây dựng được mục tiêu của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "xây dựng được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong học tập",
                        "xây dựng được kế hoạch của cá nhân để thực hiện các công việc của bản thân trong cuộc sống",
                        "xây dựng được kế hoạch kinh doanh của bản thân",
                        "xây dựng được kế hoạch thu trong gia đình",
                        "xây dựng được kế hoạch chi trong gia đình",
                        "có khả năng tham gia một số hoạt động kinh tế – xã hội phù hợp với lứa tuổi",
                        "đề xuất được giải pháp phù hợp để xử lí một số tình huống đạo đức",
                        "đề xuất được giải pháp phù hợp để xử lí một số tình huống pháp luật",
                        "đề xuất được giải pháp phù hợp để xử lí một số tình huống kinh tế",
                        "thực hiện được giải pháp phù hợp để xử lí một số tình huống đạo đức",
                        "thực hiện được giải pháp phù hợp để xử lí một số tình huống pháp luật",
                        "thực hiện được giải pháp phù hợp để xử lí một số tình huống kinh tế",
                        "lựa chọn được giải pháp phù hợp để xử lí một số tình huống đạo đức",
                        "lựa chọn được giải pháp phù hợp để xử lí một số tình huống pháp luật",
                        "lựa chọn được giải pháp phù hợp để xử lí một số tình huống kinh tế"
                    ]
                },
                "Giáo dục thể chất": {
                    "Biết": [
                        "kể được tên trò chơi vận động",
                        "kể được tên các môn thể thao",
                        "liệt kê được tên dụng cụ của các môn thể thao",
                        "nêu được tên động tác kĩ thuật",
                        "nêu được tên tư thế vận động cơ bản",
                        "phát biểu được một số điều luật thể thao",
                        "thuộc một số điều luật thể thao",
                        "xác định được các tư thế động tác",
                        "xác định được phương hướng",
                        "xác định được biên độ động tác",
                        "biết được các tư thế động tác",
                        "biết được phương hướng",
                        "biết được biên độ động tác",
                        "nhận biết được chế độ dinh dưỡng",
                        "nhận biết được các yếu tố vệ sinh",
                        "nhận biết được thiên nhiên có lợi trong tập luyện",
                        "nhận biết được thiên nhiên có hại trong tập luyện",
                        "biết được một cách sơ giản về lịch sử của môn thể thao ưa thích",
                        "khắc phục được hiện tượng cực điểm xảy ra khi chạy cự li trung bình"
                    ],
                    "Hiểu": [
                        "nêu được vai trò của vệ sinh trong tập luyện",
                        "nêu được ý nghĩa của vệ sinh trong tập luyện",
                        "mô tả được động tác kĩ thuật",
                        "so sánh được sự khác nhau giữa kĩ thuật và chiến thuật của môn thể thao",
                        "giới thiệu được những biến đổi quan trọng về phát triển các kĩ thuật môn nhảy cao",
                        "chỉ ra được nguyên nhân dẫn đến động tác sai",
                        "chỉ ra được cách khắc phục động tác sai đó",
                        "đánh giá được tầm quan trọng của các hoạt động vận động đến phát triển thể lực và sức khoẻ",
                        "phân biệt được các sơ đồ chiến thuật thi đấu một môn thể thao",
                        "so sánh được nội dung tập luyện phù hợp để nâng cao sức khoẻ",
                        "so sánh được phương pháp tập luyện phù hợp để nâng cao sức khoẻ"
                    ],
                    "Vận dụng": [
                        "thực hiện được cách chăm sóc sức khoẻ phù hợp với bản thân",
                        "hướng dẫn được người khác cách chăm sóc sức khoẻ",
                        "hướng dẫn được người khác cách bảo vệ môi trường tập luyện",
                        "rèn luyện được khả năng thích ứng của cơ thể với những biến đổi của môi trường",
                        "biểu diễn được các động tác kĩ thuật",
                        "biểu diễn được bài tập liên hoàn",
                        "tự sửa được động tác thông qua nghe",
                        "tự sửa được động tác thông qua quan sát",
                        "tự sửa được động tác thông qua tập luyện",
                        "vận dụng được các kĩ thuật đã học vào luyện tập",
                        "vận dụng được các kĩ thuật đã học vào thi đấu",
                        "áp dụng được các động tác chiến thuật hợp lí vào thi đấu",
                        "vận dụng được điều luật thể thao vào tổ chức thi đấu",
                        "đề xuất được giải pháp phù hợp cho tổ chức thi đấu",
                        "xử lí được các tình huống trong tập luyện",
                        "xử lí được các tình huống trong thi đấu",
                        "xác định được một số biện pháp phòng tránh chấn thương",
                        "lập được kế hoạch tập luyện để phát triển tố chất thể lực",
                        "lập được thời gian tập luyện để phát triển tố chất thể lực"
                    ]
                },
                "Hoạt động trải nghiệm": {
                    "Biết": [
                        "kể được những việc làm tốt",
                        "nêu được những hành động an toàn",
                        "nêu được mục tiêu lao động an toàn",
                        "nói được những hành động an toàn",
                        "nói được mục tiêu lao động an toàn",
                        "nhận biết được những việc nên làm",
                        "nhận diện được nguy hiểm",
                        "nhận diện được sở thích của bản thân",
                        "tôn trọng người khác",
                        "tôn trọng sự khác biệt",
                        "có ý thức giữ vệ sinh chung",
                        "tìm hiểu được thu nhập của người thân",
                        "tìm hiểu được công việc của bố mẹ",
                        "biết cách làm tìm kiếm sự hỗ trợ"
                    ],
                    "Hiểu": [
                        "trình bày được ước mơ nghề nghiệp",
                        "mô tả được hình ảnh bản thân",
                        "mô tả được đức tính",
                        "mô tả được vẻ đẹp thiên nhiên",
                        "giới thiệu được vẻ đẹp quê em",
                        "giới thiệu được nhân vật",
                        "giới thiệu được sự kiện",
                        "chỉ ra được ý nghĩa của hoạt động",
                        "chỉ ra được tác động của biến đổi khí hậu",
                        "phân tích được điểm mạnh",
                        "phân tích được điểm yếu",
                        "phân tích được thông tin nghề nghiệp",
                        "đánh giá được giá trị xã hội",
                        "đánh giá được hiệu quả hoạt động",
                        "nhận xét được sự tiến bộ của bản thân",
                        "nhận xét được giá trị của cá nhân"
                    ],
                    "Vận dụng": [
                        "xác định được nghề",
                        "xác định được nhóm nghề",
                        "khảo sát được nhu cầu",
                        "khảo sát được hứng thú",
                        "vận động được người thân tham gia bảo vệ môi trường",
                        "đề xuất được phương án giải quyết vấn đề",
                        "đề xuất được việc hợp tác",
                        "đưa ra được ý kiến giải quyết vấn đề",
                        "thực hiện được việc chăm sóc bản thân",
                        "làm quen được với bạn mới",
                        "làm quen được với hàng xóm",
                        "thuyết trình được",
                        "lên kế hoạch truyền thông trong cộng đồng",
                        "rèn luyện được một số đức tính",
                        "rèn luyện được thói quen",
                        "làm được công việc tự phục vụ",
                        "thể hiện được cảm xúc",
                        "thể hiện được sự đồng cảm",
                        "thể hiện được hành vi văn hoá",
                        "biết làm sử dụng công cụ lao động an toàn",
                        "biết làm chăm sóc sức khoẻ",
                        "thiết lập được quan hệ",
                        "xây dựng được quan hệ",
                        "xây dựng được tình bạn",
                        "xây dựng được chiến dịch truyền thông",
                        "tổ chức được sự kiện",
                        "tổ chức được buổi lao động",
                        "ứng phó được với căng thẳng",
                        "ứng phó được với thiên tai"
                    ]
                },
                "Tự nhiên và Xã hội": {
                    "Biết": [
                        "nêu được công việc của người dân trong cộng đồng",
                        "nêu được đóng góp của công việc đó cho xã hội",
                        "kể được tên các hoạt động chính trong lớp học",
                        "kể được tên các hoạt động chính trong trường học",
                        "nói được tên trường",
                        "nói được địa chỉ của trường",
                        "nói được tên lớp",
                        "nói được vị trí của lớp học trong trường",
                        "nhận biết được tên gọi các bộ phận bên ngoài của cơ thể",
                        "nhận biết được chức năng các bộ phận bên ngoài của cơ thể",
                        "nhận biết được các giác quan của cơ thể",
                        "xác định được các hoạt động vận động có lợi cho sức khoẻ",
                        "xác định được các hoạt động nghỉ ngơi có lợi cho sức khoẻ",
                        "xác định được một số tình huống nguy hiểm có thể xảy ra trong khi tham gia các hoạt động ở trường",
                        "xác định được một số rủi ro có thể xảy ra trong khi tham gia các hoạt động ở trường",
                        "xác định được cách phòng tránh một số tình huống nguy hiểm có thể xảy ra trong khi tham gia các hoạt động ở trường",
                        "xác định được cách phòng tránh một số rủi ro có thể xảy ra trong khi tham gia các hoạt động ở trường"
                    ],
                    "Hiểu": [
                        "mô tả được một số hiện tượng thiên tai",
                        "vẽ được đường thời gian theo thứ tự các sự kiện lớn đã xảy ra trong gia đình",
                        "vẽ được đường thời gian theo thứ tự các mốc quan trọng đã xảy ra trong gia đình",
                        "giới thiệu được một cách đơn giản về truyền thống nhà trường",
                        "trình bày được một số việc cần làm để giữ gìn cơ quan tiêu hoá",
                        "trình bày được một số việc cần tránh để giữ gìn cơ quan tiêu hoá",
                        "trình bày được một số việc cần làm để bảo vệ cơ quan tiêu hoá",
                        "trình bày được một số việc cần tránh để bảo vệ cơ quan tiêu hoá",
                        "trình bày được một số việc cần làm để giữ gìn cơ quan tuần hoàn",
                        "trình bày được một số việc cần tránh để giữ gìn cơ quan tuần hoàn",
                        "trình bày được một số việc cần làm để bảo vệ cơ quan tuần hoàn",
                        "trình bày được một số việc cần tránh để bảo vệ cơ quan tuần hoàn",
                        "trình bày được một số việc cần làm để giữ gìn thần kinh",
                        "trình bày được một số việc cần tránh để giữ gìn thần kinh",
                        "trình bày được một số việc cần làm để bảo vệ thần kinh",
                        "trình bày được một số việc cần tránh để bảo vệ thần kinh",
                        "nêu được ví dụ về việc sử dụng thực vật trong đời sống hằng ngày",
                        "nêu được ví dụ về việc sử dụng động vật trong đời sống hằng ngày",
                        "so sánh được đặc điểm cấu tạo của một số động vật khác nhau",
                        "phân loại được thực vật dựa trên một số tiêu chí",
                        "phân loại được thực vật dựa trên đặc điểm của thân",
                        "phân loại được thực vật dựa trên đặc điểm của rễ",
                        "phân loại được thực vật dựa trên đặc điểm của lá"
                    ],
                    "Vận dụng": [
                        "nhận xét được sự thay đổi của gia đình theo thời gian qua một số ví dụ",
                        "đặt được câu hỏi để tìm hiểu về truyền thống nhà trường",
                        "đặt được câu hỏi để tìm hiểu về năm thành lập trường",
                        "đặt được câu hỏi để tìm hiểu về thành tích dạy và học",
                        "đặt được câu hỏi để tìm hiểu về các hoạt động khác",
                        "giải thích được một cách đơn giản tại sao cần phải giữ vệ sinh xung quanh nhà",
                        "thực hiện được nhiệm vụ khảo sát về sự an toàn liên quan đến cơ sở vật chất của nhà trường",
                        "thực hiện được nhiệm vụ khảo sát về sự an toàn liên quan đến khu vực xung quanh trường theo sự phân công của nhóm",
                        "thực hiện được đi đúng tư thế để phòng tránh cong vẹo cột sống",
                        "thực hiện được đứng đúng tư thế để phòng tránh cong vẹo cột sống",
                        "thực hiện được ngồi đúng tư thế để phòng tránh cong vẹo cột sống",
                        "thực hiện được mang cặp đúng tư thế để phòng tránh cong vẹo cột sống",
                        "đưa ra được cách xử lí tình huống khi học sinh bị ngộ độc",
                        "đưa ra được cách xử lí tình huống khi người nhà bị ngộ độc",
                        "đưa ra được cách ứng xử phù hợp trong tình huống giả định có cháy xảy ra",
                        "đưa ra được nhận xét về những cách ứng xử đó",
                        "đề xuất cách sử dụng thực vật hợp lí",
                        "đề xuất cách sử dụng động vật hợp lí"
                    ]
                }
            }
        }

class KnowledgeBase:
    def __init__(self):
        self.student_assessments = StudentAssessments()